# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Test.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nTest.proto\" \n\x13ServerStreamRequest\x12\t\n\x01n\x18\x01 \x01(\x05\"\x1a\n\x0bTestRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x1d\n\x0cTestResponse\x12\r\n\x05reply\x18\x01 \x01(\t\"$\n\x14\x46ileUploadRequestStr\x12\x0c\n\x04path\x18\x01 \x01(\t\"\"\n\x11\x46ileUploadRequest\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\"2\n\x12\x46ileUploadResponse\x12\x0e\n\x06length\x18\x01 \x01(\x05\x12\x0c\n\x04time\x18\x02 \x01(\t\"K\n\x14\x43lientStreamResponse\x12\x13\n\x0bnoOfRequest\x18\x01 \x01(\x05\x12\x1e\n\x08requests\x18\x02 \x03(\x0b\x32\x0c.TestRequest2\xde\x02\n\x0bTestService\x12+\n\x0cUnaryRequest\x12\x0c.TestRequest\x1a\r.TestResponse\x12\x38\n\x0fServerStreaming\x12\x14.ServerStreamRequest\x1a\r.TestResponse0\x01\x12\x38\n\x0f\x43lientStreaming\x12\x0c.TestRequest\x1a\x15.ClientStreamResponse(\x01\x12\x37\n\x14\x42iDirectionalRequest\x12\x0c.TestRequest\x1a\r.TestResponse(\x01\x30\x01\x12\x37\n\nFileUpload\x12\x12.FileUploadRequest\x1a\x13.FileUploadResponse(\x01\x12<\n\x0e\x46ileUploadTest\x12\x15.FileUploadRequestStr\x1a\x13.FileUploadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Test_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SERVERSTREAMREQUEST']._serialized_start=14
  _globals['_SERVERSTREAMREQUEST']._serialized_end=46
  _globals['_TESTREQUEST']._serialized_start=48
  _globals['_TESTREQUEST']._serialized_end=74
  _globals['_TESTRESPONSE']._serialized_start=76
  _globals['_TESTRESPONSE']._serialized_end=105
  _globals['_FILEUPLOADREQUESTSTR']._serialized_start=107
  _globals['_FILEUPLOADREQUESTSTR']._serialized_end=143
  _globals['_FILEUPLOADREQUEST']._serialized_start=145
  _globals['_FILEUPLOADREQUEST']._serialized_end=179
  _globals['_FILEUPLOADRESPONSE']._serialized_start=181
  _globals['_FILEUPLOADRESPONSE']._serialized_end=231
  _globals['_CLIENTSTREAMRESPONSE']._serialized_start=233
  _globals['_CLIENTSTREAMRESPONSE']._serialized_end=308
  _globals['_TESTSERVICE']._serialized_start=311
  _globals['_TESTSERVICE']._serialized_end=661
# @@protoc_insertion_point(module_scope)
